server:
  port: 6080

spring:
  datasource:
    druid:
      username: root
      password: admin123456
      url: jdbc:mysql://localhost:3306/vuedata?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 8
      max-active: 16
      min-idle: 1
      max-wait: 60000

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,"

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
        url-pattern: /druid/*

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.protransfer.procurementtransfer.entity

logging:
  level:
    me:
      leehao:
        mybatisdemo:
          mapper : debug
